# fly.toml app configuration file generated for vt-notes-full on 2023-11-27T14:03:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vt-notes-full"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
